name: GitHub Pages Configuration

url: https://deck-ar.vercel.app
baseurl: ""

source: .
branch: gh-pages

exclude:
  - .github/
  - node_modules/
  - package.json
  - package-lock.json
  - README.md

include:
  - deck-admin/
  - public/
  - pages/
  - js/
  - css/
  - index.html